//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionsViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literals() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolutionsViewer.Properties.Literals", typeof(Literals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print Hello and Name ähnelt.
        /// </summary>
        public static string BasicExercises_01 {
            get {
                return ResourceManager.GetString("BasicExercises_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sum of Two Numbers ähnelt.
        /// </summary>
        public static string BasicExercises_02 {
            get {
                return ResourceManager.GetString("BasicExercises_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Divide Two Numbers ähnelt.
        /// </summary>
        public static string BasicExercises_03 {
            get {
                return ResourceManager.GetString("BasicExercises_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specified Operations Results ähnelt.
        /// </summary>
        public static string BasicExercises_04 {
            get {
                return ResourceManager.GetString("BasicExercises_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swap Two Numbers ähnelt.
        /// </summary>
        public static string BasicExercises_05 {
            get {
                return ResourceManager.GetString("BasicExercises_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multiply Three Numbers ähnelt.
        /// </summary>
        public static string BasicExercises_06 {
            get {
                return ResourceManager.GetString("BasicExercises_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arithmetic Operations ähnelt.
        /// </summary>
        public static string BasicExercises_07 {
            get {
                return ResourceManager.GetString("BasicExercises_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multiplication Table ähnelt.
        /// </summary>
        public static string BasicExercises_08 {
            get {
                return ResourceManager.GetString("BasicExercises_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average of Four Numbers ähnelt.
        /// </summary>
        public static string BasicExercises_09 {
            get {
                return ResourceManager.GetString("BasicExercises_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specified Formula with Three Numbers ähnelt.
        /// </summary>
        public static string BasicExercises_10 {
            get {
                return ResourceManager.GetString("BasicExercises_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print Age Message ähnelt.
        /// </summary>
        public static string BasicExercises_11 {
            get {
                return ResourceManager.GetString("BasicExercises_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repeat Number in Rows ähnelt.
        /// </summary>
        public static string BasicExercises_12 {
            get {
                return ResourceManager.GetString("BasicExercises_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rectangle Pattern with Number ähnelt.
        /// </summary>
        public static string BasicExercises_13 {
            get {
                return ResourceManager.GetString("BasicExercises_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Celsius to Kelvin and Fahrenheit ähnelt.
        /// </summary>
        public static string BasicExercises_14 {
            get {
                return ResourceManager.GetString("BasicExercises_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Basic Exercises ähnelt.
        /// </summary>
        public static string Categories_01 {
            get {
                return ResourceManager.GetString("Categories_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Integers only! ähnelt.
        /// </summary>
        public static string Error_IntegersOnly {
            get {
                return ResourceManager.GetString("Error_IntegersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid input. Please enter valid numbers. ähnelt.
        /// </summary>
        public static string Error_InvalidNumbers {
            get {
                return ResourceManager.GetString("Error_InvalidNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Age ähnelt.
        /// </summary>
        public static string FieldCaption_Age {
            get {
                return ResourceManager.GetString("FieldCaption_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ° Celsius ähnelt.
        /// </summary>
        public static string FieldCaption_Celsius {
            get {
                return ResourceManager.GetString("FieldCaption_Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string FieldCaption_Name {
            get {
                return ResourceManager.GetString("FieldCaption_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number ähnelt.
        /// </summary>
        public static string FieldCaption_Number {
            get {
                return ResourceManager.GetString("FieldCaption_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number 1 ähnelt.
        /// </summary>
        public static string FieldCaption_Number1 {
            get {
                return ResourceManager.GetString("FieldCaption_Number1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number 2 ähnelt.
        /// </summary>
        public static string FieldCaption_Number2 {
            get {
                return ResourceManager.GetString("FieldCaption_Number2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number 3 ähnelt.
        /// </summary>
        public static string FieldCaption_Number3 {
            get {
                return ResourceManager.GetString("FieldCaption_Number3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number 4 ähnelt.
        /// </summary>
        public static string FieldCaption_Number4 {
            get {
                return ResourceManager.GetString("FieldCaption_Number4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die x ähnelt.
        /// </summary>
        public static string FieldCaption_NumberX {
            get {
                return ResourceManager.GetString("FieldCaption_NumberX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die y ähnelt.
        /// </summary>
        public static string FieldCaption_NumberY {
            get {
                return ResourceManager.GetString("FieldCaption_NumberY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die z ähnelt.
        /// </summary>
        public static string FieldCaption_NumberZ {
            get {
                return ResourceManager.GetString("FieldCaption_NumberZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programming Exercises Solutions Viewer ähnelt.
        /// </summary>
        public static string MainView_Title {
            get {
                return ResourceManager.GetString("MainView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result ähnelt.
        /// </summary>
        public static string Output_Label {
            get {
                return ResourceManager.GetString("Output_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        public static string StartButton_Caption {
            get {
                return ResourceManager.GetString("StartButton_Caption", resourceCulture);
            }
        }
    }
}
